### ISSUE TITLE
NYT Digits Solver missing solutions

### ISSUE THREAD

**Issue by yjian012** [Mocha2007/mocha2007.github.io#82]
The problem is, if you simply permute the numbers and operators and evaluate the expression, you'll miss many valid expressions which requires parentheses. E.g., 9 1 1 1 1 1 1 has the solution 9=(1+1+1)*(1+1+1), but you can't get it without parentheses. 

I wanted to write a Digits solver myself, so I was quite disappointed when I noticed that someone beat me to it.  But I found this bug, so I did a correct implementation myself XD , I posted it here https://yjian012.github.io/Yi-blog/2023/04/23/NewYorkTimesDigitsSolver.html . I'm a beginner on JS, so please show me if there are better ways to write JS codes!

**Comment by Mocha2007** [comment]
@yjian012 You are absolutely right - I eventually realized this would be a problem, but was intrigued as to why I never had this issue. I tried looking at the source for Digits, but it seems the code for puzzle generation is unfinished, and it just uses a pre-generated database of puzzles for the first 60 days... based on the pre-generated puzzles though, it *might* be sufficient to just permute the operators... but on the other hand, the (incomplete) puzzle code suggests the following will be how puzzles are generated once the beta is up:

1. select two numbers from the original set and apply a valid operation to them
2. select another number from the original set and apply an operation between that and the result of (1) - this is the target
3. generate three random numbers as decoys

If this ends up being the case, then permutation will definitely be insufficient, and would probably only work like 60-70% of the time. But it looks how the temporary puzzles were generated is to take five random numbers and insert operations between them (without parens), and then add a random sixth number as a decoy (although this is just a guess...).

In any case, I'm going to wait until the beta is over and they finalize the generation before figuring out how to proceed.

As a sidenote, I suspect the lack of division in NYT's puzzles has to do with a bug in the code limiting operations to whatever is valid between the first two numbers. There is a part of the generation code that looks like it's supposed to generate random operations between adjacent pairs of numbers, but just uses the first two numbers instead. This may have been carried over from whatever function generated the test puzzles. Out of 893 operations used in the hints for the beta puzzles, only 21 are division, which seems extremely low.

**Comment by Mocha2007** [comment]
Also, I just noticed the day 4 level 5 puzzle hint says you need to do 3/3 even though there's only one 3, lol.

**Comment by Mocha2007** [comment]
Addendum:

Here is the distribution of operations in the solutions provided by the NYT:

`+	319`
`-	157`
`*	396`
`/	21`

The weights in the random operator generator function they use are these:
`+	20%`
`-	20% (if - is valid)`
`*	25%`
`/	35% (if / is valid)`

**Comment by yjian012** [comment]
Aha! I hadn't looked into their code. I just took a look, I think the low percentage of division is expected, because it would be very rare for two random numbers from 0-99 to have an integer quotient (~5.75% from my simulation).
If you multiply 35% and 5.75%, you get ~2.01%. The actual frequency is ~2.35%, which is close. It also explains why the frequency of '-' is about half of '+', it's because half of the time they try to use the small number to subtract the large number...

And this part of the code:
```
else {
    return getSmartOperation(firstNum, secondNum)
  }
```
is just terrible XD, half of the time the first number is smaller than the second number, there's no point in putting them back into the function.
What's worse is, if the first number < the second number and their sum > 999 and their product > 999, it would be an infinite recursion...
A better way is to exchange the two numbers if the first is smaller, then first try division with high probability, if it doesn't work, attempt to '+' or '*', if the result is larger than 999, just do '-' which guarantees to be valid. There's no need to put them back into the function 🤦

**Comment by Mocha2007** [comment]
NYT unfortunately does not offer this game anymore
